export type FactionId = "greece" | "germany" | "france" | "britain";
export type Terrain = "ground" | "highland";
export type RoleId = "tank" | "support" | "sniper" | "caster" | "controller";
export type SkillId = "socratic" | "plato" | "aristotle" | "epicurus" | "kant" | "fichte" | "schelling" | "hegel" | "husserl" | "heidegger" | "descartes" | "rousseau" | "sartre" | "foucault" | "locke" | "hume" | "hobbes" | "russell" | "althusser" | "bacon" | "bentham" | "deleuze" | "derrida" | "lacan" | "wittgenstein";

export type Character = {
  id: string;
  name: string;
  cost: 1 | 2 | 3 | 4;
  faction: FactionId;
  factionLabel: string;
  profession: string;
  terrain: Terrain;
  block: number;
  role: { id: RoleId; label: string; cue: string };
  portrait: string;
  stats: { resolve: number; insight: number; guard: number };
  combat: { damage: number; attackEvery: number; range: number; maxEnergy: number; attackEnergy: number };
  skill: { id: SkillId; name: string; summary: string; power: number };
};

const greek = "古希腊"; const german = "德国"; const french = "法国"; const british = "英国";

/**
 * V0.2 currently exposes the stable V0.1 roster plus the vertical-slice units.
 * Remaining frozen-design units are added only after the combat foundation is proven.
 */
export const characters: Character[] = [
  { id: "socrates", name: "苏格拉底", cost: 1, faction: "greece", factionLabel: greek, profession: "地面控场", terrain: "ground", block: 1, role: { id: "controller", label: "控场", cue: "反诘" }, portrait: "◎", stats: { resolve: 590, insight: 42, guard: 24 }, combat: { damage: 28, attackEvery: 7, range: 1, maxEnergy: 70, attackEnergy: 18 }, skill: { id: "socratic", name: "反诘", summary: "减能、停顿并施加矛盾", power: 1 } },
  { id: "plato", name: "柏拉图", cost: 2, faction: "greece", factionLabel: greek, profession: "地面控场", terrain: "ground", block: 1, role: { id: "controller", label: "控场", cue: "洞穴寓言" }, portrait: "◇", stats: { resolve: 730, insight: 58, guard: 34 }, combat: { damage: 31, attackEvery: 8, range: 2, maxEnergy: 80, attackEnergy: 16 }, skill: { id: "plato", name: "洞穴寓言", summary: "冻结尚未接敌的后续敌群", power: 1 } },
  { id: "aristotle", name: "亚里士多德", cost: 2, faction: "greece", factionLabel: greek, profession: "高台狙击", terrain: "highland", block: 0, role: { id: "sniper", label: "狙击", cue: "四因追问" }, portrait: "⌁", stats: { resolve: 440, insight: 72, guard: 18 }, combat: { damage: 44, attackEvery: 8, range: 8, maxEnergy: 75, attackEnergy: 17 }, skill: { id: "aristotle", name: "四因追问", summary: "连续解析最高生命敌人并破甲", power: 1 } },
  { id: "epicurus", name: "伊壁鸠鲁", cost: 1, faction: "greece", factionLabel: greek, profession: "地面辅助", terrain: "ground", block: 1, role: { id: "support", label: "治疗", cue: "花园宁静" }, portrait: "✚", stats: { resolve: 570, insight: 48, guard: 26 }, combat: { damage: 22, attackEvery: 8, range: 2, maxEnergy: 70, attackEnergy: 17 }, skill: { id: "epicurus", name: "花园宁静", summary: "治疗最低生命友军，满血时提供护盾", power: 1 } },
  { id: "fichte", name: "费希特", cost: 1, faction: "germany", factionLabel: german, profession: "地面重装", terrain: "ground", block: 2, role: { id: "tank", label: "重装", cue: "自我设定" }, portrait: "▣", stats: { resolve: 840, insight: 34, guard: 48 }, combat: { damage: 30, attackEvery: 7, range: 1, maxEnergy: 65, attackEnergy: 18 }, skill: { id: "fichte", name: "自我设定", summary: "获得护盾，护盾存在时增加阻挡", power: 1 } },
  { id: "husserl", name: "胡塞尔", cost: 2, faction: "germany", factionLabel: german, profession: "地面辅助", terrain: "ground", block: 1, role: { id: "support", label: "治疗", cue: "现象学还原" }, portrait: "◉", stats: { resolve: 650, insight: 66, guard: 28 }, combat: { damage: 24, attackEvery: 8, range: 2, maxEnergy: 78, attackEnergy: 16 }, skill: { id: "husserl", name: "现象学还原", summary: "治疗、净化，无伤员时提供护盾", power: 1 } },
  { id: "schelling", name: "谢林", cost: 3, faction: "germany", factionLabel: german, profession: "高台群攻", terrain: "highland", block: 0, role: { id: "caster", label: "群攻", cue: "世界时代" }, portrait: "✦", stats: { resolve: 500, insight: 86, guard: 20 }, combat: { damage: 57, attackEvery: 9, range: 7, maxEnergy: 90, attackEnergy: 15 }, skill: { id: "schelling", name: "世界时代", summary: "减速、持续伤害与区域爆发", power: 1 } },
  { id: "heidegger", name: "海德格尔", cost: 3, faction: "germany", factionLabel: german, profession: "地面重装", terrain: "ground", block: 3, role: { id: "tank", label: "重装", cue: "向死而在" }, portrait: "⬡", stats: { resolve: 1080, insight: 46, guard: 64 }, combat: { damage: 45, attackEvery: 8, range: 1, maxEnergy: 85, attackEnergy: 16 }, skill: { id: "heidegger", name: "向死而在", summary: "每波一次濒死不死、嘲讽和强化阻挡", power: 1 } },
  { id: "kant", name: "康德", cost: 4, faction: "germany", factionLabel: german, profession: "高台单体", terrain: "highland", block: 0, role: { id: "controller", label: "控场", cue: "物自体" }, portrait: "△", stats: { resolve: 560, insight: 98, guard: 24 }, combat: { damage: 52, attackEvery: 8, range: 8, maxEnergy: 100, attackEnergy: 15 }, skill: { id: "kant", name: "物自体", summary: "封锁高威胁目标并造成延迟伤害", power: 1 } },
  { id: "hegel", name: "黑格尔", cost: 4, faction: "germany", factionLabel: german, profession: "高台群攻", terrain: "highland", block: 0, role: { id: "caster", label: "群攻", cue: "扬弃" }, portrait: "◈", stats: { resolve: 590, insight: 104, guard: 26 }, combat: { damage: 72, attackEvery: 9, range: 8, maxEnergy: 95, attackEnergy: 16 }, skill: { id: "hegel", name: "扬弃", summary: "范围伤害并施加、引爆和传播矛盾", power: 1 } },
  { id: "descartes", name: "笛卡尔", cost: 1, faction: "france", factionLabel: french, profession: "高台单体", terrain: "highland", block: 0, role: { id: "controller", label: "单体", cue: "我思故我在" }, portrait: "✧", stats: { resolve: 455, insight: 58, guard: 18 }, combat: { damage: 35, attackEvery: 7, range: 7, maxEnergy: 65, attackEnergy: 18 }, skill: { id: "descartes", name: "我思故我在", summary: "免疫控制并无视部分防御", power: 1 } },
  { id: "rousseau", name: "卢梭", cost: 1, faction: "france", factionLabel: french, profession: "地面辅助", terrain: "ground", block: 1, role: { id: "support", label: "支援", cue: "社会契约" }, portrait: "❖", stats: { resolve: 680, insight: 60, guard: 31 }, combat: { damage: 25, attackEvery: 8, range: 2, maxEnergy: 72, attackEnergy: 18 }, skill: { id: "rousseau", name: "社会契约", summary: "连接地面友军，共享护盾并安全分摊伤害", power: 1 } },
  { id: "sartre", name: "萨特", cost: 2, faction: "france", factionLabel: french, profession: "地面战士", terrain: "ground", block: 1, role: { id: "controller", label: "战士", cue: "自由选择" }, portrait: "◇", stats: { resolve: 820, insight: 74, guard: 39 }, combat: { damage: 48, attackEvery: 7, range: 2, maxEnergy: 82, attackEnergy: 17 }, skill: { id: "sartre", name: "自由选择", summary: "开战按站位锁定攻击或保护形态", power: 1 } },
  { id: "foucault", name: "福柯", cost: 2, faction: "france", factionLabel: french, profession: "高台控制", terrain: "highland", block: 0, role: { id: "controller", label: "控场", cue: "全景监狱" }, portrait: "⌘", stats: { resolve: 500, insight: 76, guard: 21 }, combat: { damage: 43, attackEvery: 9, range: 8, maxEnergy: 88, attackEnergy: 16 }, skill: { id: "foucault", name: "全景监狱", summary: "区域减速、降攻并阻碍充能", power: 1 } },
  { id: "locke", name: "洛克", cost: 1, faction: "britain", factionLabel: british, profession: "地面辅助", terrain: "ground", block: 1, role: { id: "support", label: "支援", cue: "权利边界" }, portrait: "▱", stats: { resolve: 610, insight: 46, guard: 29 }, combat: { damage: 25, attackEvery: 8, range: 2, maxEnergy: 64, attackEnergy: 19 }, skill: { id: "locke", name: "权利边界", summary: "护盾并抵挡一次控制", power: 1 } },
  { id: "hume", name: "休谟", cost: 2, faction: "britain", factionLabel: british, profession: "高台辅助", terrain: "highland", block: 0, role: { id: "support", label: "支援", cue: "因果律" }, portrait: "⌁", stats: { resolve: 455, insight: 74, guard: 17 }, combat: { damage: 46, attackEvery: 8, range: 8, maxEnergy: 74, attackEnergy: 18 }, skill: { id: "hume", name: "因果律", summary: "基础伤害减速，并可模仿标准友军效果", power: 1 } },
  { id: "hobbes", name: "霍布斯", cost: 3, faction: "britain", factionLabel: british, profession: "地面重装", terrain: "ground", block: 3, role: { id: "tank", label: "重装", cue: "利维坦" }, portrait: "⬟", stats: { resolve: 1050, insight: 43, guard: 62 }, combat: { damage: 41, attackEvery: 8, range: 1, maxEnergy: 82, attackEnergy: 17 }, skill: { id: "hobbes", name: "利维坦", summary: "按阻挡总重量获得护盾、防御和嘲讽", power: 1 } },
  { id: "russell", name: "罗素", cost: 3, faction: "britain", factionLabel: british, profession: "高台单体", terrain: "highland", block: 0, role: { id: "sniper", label: "单体", cue: "逻辑原子" }, portrait: "⊞", stats: { resolve: 540, insight: 91, guard: 22 }, combat: { damage: 65, attackEvery: 9, range: 8, maxEnergy: 94, attackEnergy: 16 }, skill: { id: "russell", name: "逻辑原子", summary: "安全拆分重型目标；无法拆分时造成高额伤害", power: 1 } },
  { id: "althusser", name: "阿尔都塞", cost: 4, faction: "france", factionLabel: french, profession: "高台辅助", terrain: "highland", block: 0, role: { id: "support", label: "辅助", cue: "来日方长" }, portrait: "◫", stats: { resolve: 575, insight: 99, guard: 24 }, combat: { damage: 54, attackEvery: 9, range: 8, maxEnergy: 96, attackEnergy: 16 }, skill: { id: "althusser", name: "来日方长", summary: "三秒后在记录位置造成范围伤害和减速", power: 1 } },
  { id: "bacon", name: "培根", cost: 1, faction: "britain", factionLabel: british, profession: "高台射手", terrain: "highland", block: 0, role: { id: "sniper", label: "射手", cue: "科学归纳" }, portrait: "⌁", stats: { resolve: 470, insight: 62, guard: 17 }, combat: { damage: 39, attackEvery: 7, range: 8, maxEnergy: 68, attackEnergy: 18 }, skill: { id: "bacon", name: "科学归纳", summary: "第三次连续攻击同一目标造成额外伤害", power: 1 } },
  { id: "bentham", name: "边沁", cost: 2, faction: "britain", factionLabel: british, profession: "地面辅助", terrain: "ground", block: 1, role: { id: "support", label: "辅助", cue: "功利主义" }, portrait: "⊕", stats: { resolve: 690, insight: 68, guard: 32 }, combat: { damage: 27, attackEvery: 8, range: 2, maxEnergy: 82, attackEnergy: 16 }, skill: { id: "bentham", name: "功利主义", summary: "按最大生命比例重新平均存活友军生命并自疗", power: 1 } },
  { id: "deleuze", name: "德勒兹", cost: 3, faction: "france", factionLabel: french, profession: "高台群攻", terrain: "highland", block: 0, role: { id: "caster", label: "群攻", cue: "根茎" }, portrait: "✣", stats: { resolve: 520, insight: 88, guard: 21 }, combat: { damage: 55, attackEvery: 8, range: 8, maxEnergy: 90, attackEnergy: 16 }, skill: { id: "deleuze", name: "根茎", summary: "连接敌人并传播伤害与基础减益", power: 1 } },
  { id: "derrida", name: "德里达", cost: 3, faction: "france", factionLabel: french, profession: "高台控制", terrain: "highland", block: 0, role: { id: "controller", label: "控制", cue: "解构" }, portrait: "⌘", stats: { resolve: 510, insight: 90, guard: 20 }, combat: { damage: 51, attackEvery: 8, range: 8, maxEnergy: 88, attackEnergy: 17 }, skill: { id: "derrida", name: "解构", summary: "拆除护盾或强化；否则削弱并延后技能", power: 1 } },
  { id: "lacan", name: "拉康", cost: 4, faction: "france", factionLabel: french, profession: "高台控制", terrain: "highland", block: 0, role: { id: "controller", label: "控制", cue: "精神分析" }, portrait: "◌", stats: { resolve: 560, insight: 102, guard: 23 }, combat: { damage: 59, attackEvery: 8, range: 8, maxEnergy: 96, attackEnergy: 16 }, skill: { id: "lacan", name: "精神分析", summary: "记录威胁目标承伤并在施法或到期时引爆", power: 1 } },
  { id: "wittgenstein", name: "维特根斯坦", cost: 4, faction: "britain", factionLabel: british, profession: "高台控制", terrain: "highland", block: 0, role: { id: "controller", label: "控制", cue: "不可言说" }, portrait: "∴", stats: { resolve: 545, insight: 101, guard: 22 }, combat: { damage: 61, attackEvery: 8, range: 8, maxEnergy: 94, attackEnergy: 16 }, skill: { id: "wittgenstein", name: "不可言说", summary: "封锁特殊能力；无特殊能力时爆发并禁止获盾", power: 1 } },
];

export const characterById: Record<string, Character> = Object.fromEntries(characters.map((unit) => [unit.id, unit]));
